import Link from 'next/link';
import { ChevronLeft, FileText } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col font-sans bg-[#F9FAFB]">
      <header className="bg-white border-b border-slate-200 sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/" className="text-slate-400 hover:text-[#0F172A] p-2 -ml-2 rounded-md hover:bg-slate-100">
              <ChevronLeft className="w-5 h-5" />
            </Link>
            <div className="h-6 w-px bg-slate-200"></div>
            <h1 className="text-lg font-bold text-[#0F172A] flex items-center gap-2">
              <FileText className="w-5 h-5 text-[#C6A87C]" />
              Terms of Use
            </h1>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 w-full">
        <div className="gov-card p-8 sm:p-12">
          <h2 className="text-3xl font-extrabold text-[#0F172A] mb-2">Terms of Use</h2>
          <p className="text-sm text-slate-400 mb-10">Last updated: July 20, 2026</p>

          <div className="space-y-8 text-slate-600 leading-relaxed">
            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">1. Acceptance of Terms</h3>
              <p>
                By accessing or using the Oasis.ai Portal (&ldquo;the Platform&rdquo;), you agree to be bound by these
                Terms of Use. If you do not agree to these terms, please do not use the Platform.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">2. Description of Service</h3>
              <p>
                Oasis.ai provides AI-assisted informational tools for foreign investors exploring corporate
                relocation, company setup, document review, business matchmaking, and banking introductions in
                Dubai. The Platform is a demonstration and advisory tool; it does not file, submit, or execute any
                government or banking transaction on your behalf.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">3. No Professional Advice</h3>
              <p>
                Outputs generated by the Platform&apos;s AI agents (including relocation guidance, tax estimates,
                document audits, and banking matches) are provided for general informational purposes only and do
                not constitute legal, financial, tax, or immigration advice. You should consult a licensed
                professional before making business or investment decisions.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">4. User Responsibilities</h3>
              <p>
                You agree to provide accurate information when using the Platform, to use the service only for
                lawful purposes, and not to attempt to disrupt, reverse-engineer, or gain unauthorized access to
                the Platform or its underlying systems.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">5. Intellectual Property</h3>
              <p>
                All content, branding, and software associated with the Platform, excluding documents you upload,
                remain the property of Oasis.ai and its licensors. You may not copy, redistribute, or create
                derivative works from the Platform without prior written consent.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">6. Limitation of Liability</h3>
              <p>
                The Platform is provided &ldquo;as is&rdquo; without warranties of any kind. Oasis.ai is not liable
                for any indirect, incidental, or consequential damages arising from your use of, or inability to
                use, the Platform.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">7. Governing Law</h3>
              <p>
                These Terms are governed by the laws applicable in the Emirate of Dubai and the federal laws of the
                United Arab Emirates, without regard to conflict-of-law principles.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">8. Changes to These Terms</h3>
              <p>
                We may update these Terms of Use from time to time. Continued use of the Platform after changes are
                posted constitutes acceptance of the revised terms.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold text-[#0F172A] mb-2">9. Contact Us</h3>
              <p>
                Questions about these Terms can be directed to the Oasis.ai support team through the{' '}
                <Link href="/page/support" className="text-[#C6A87C] font-medium hover:underline">
                  Help &amp; Support
                </Link>{' '}
                center.
              </p>
            </section>
          </div>

          <div className="mt-12 pt-8 border-t border-slate-100">
            <Link
              href="/"
              className="inline-flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-[#0F172A] hover:bg-[#1e293b] transition-colors"
            >
              Return to Homepage
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
